name: juniper
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  simple_icons: ^10.1.3
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  dio: ^5.7.0
  enefty_icons: ^1.0.7
  meta: ^1.15.0
  flutter_rating_stars: ^1.1.0
  flutter_svg: ^2.0.16
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.2
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.3
  go_router: ^14.8.1 # Update to latest version
  intl: ^0.20.1
  image_picker: ^1.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  tab_container: ^3.5.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  fl_chart: ^0.70.2
  bloc_concurrency: ^0.2.5
  logging: ^1.3.0
  rxdart: ^0.28.0
  chat_bubbles: ^1.7.0
  supabase_flutter: ^2.8.4
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/properties/
    - assets/fonts/
    - assets/icons/
    - assets/icons/linear/
    - assets/icons/bold/
    - lib/features/home/data/datasources/
    - lib/features/home/data/datasources/response.json
    - lib/features/profile/data/datasources/
    - assets/animations/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueUltraLight.otf
          weight: 100
        - asset: assets/fonts/HelveticaNeueThin.otf
          weight: 200
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          weight: 800
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 900
